version: '3.7'

services:
  
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
     - SERVICES=s3,sns,sqs
     - DEFAULT_REGION=eu-west-2
     - DATA_DIR=/tmp/localstack/data
    ports:
     - "4572:4572"
     - "9999:8080"
    volumes:
      - localstack-data:/tmp/localstack

volumes:

  localstack-data:
    name: localstack-data